/* Baba Catalogue 2026 — service worker.
   Assets are separate files (sprite, 28 page images, icons). Strategy:
     - navigations: cache-first, falling back to network, then to cached index
     - everything else in scope: cache-first with background fill
   CACHE_VERSION and PRECACHE are GENERATED by build.py from the real file list
   and a content hash — do not edit them by hand. */

const CACHE_VERSION = '2026-0819-ccc8e04991';
const CACHE = 'baba-catalogue-' + CACHE_VERSION;

const PRECACHE = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./sprite.webp",
  "./logo.png",
  "./qr.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-512.png",
  "./apple-touch-icon.png",
  "./favicon-32.png",
  "./favicon-16.png",
  "./favicon.ico",
  "./page-01.webp",
  "./page-02.webp",
  "./page-03.webp",
  "./page-04.webp",
  "./page-05.webp",
  "./page-06.webp",
  "./page-07.webp",
  "./page-08.webp",
  "./page-09.webp",
  "./page-10.webp",
  "./page-11.webp",
  "./page-12.webp",
  "./page-13.webp",
  "./page-14.webp",
  "./page-15.webp",
  "./page-16.webp",
  "./page-17.webp",
  "./page-18.webp",
  "./page-19.webp",
  "./page-20.webp",
  "./page-21.webp",
  "./page-22.webp",
  "./page-23.webp",
  "./page-24.webp",
  "./page-25.webp",
  "./page-26.webp",
  "./page-27.webp",
  "./page-28.webp",
  "./font-400.woff2",
  "./font-700.woff2",
  "./products-extra.json",
  "./badges.webp"
];

/* High-resolution product images. Not precached — they would double the first
   download. They are fetched the first time someone taps to enlarge, and the
   fetch handler below caches them from then on. Listed here so the deploy
   checker can still confirm they were uploaded. */
const LAZY = [
  "./detail-0.webp",
  "./detail-1.webp",
  "./detail-2.webp",
  "./detail-3.webp",
  "./detail-4.webp",
  "./detail-5.webp",
  "./detail-6.webp"
];

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Add individually: one 404 (e.g. a missing icon) must not fail the whole install.
    await Promise.all(PRECACHE.map(async url => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (e) { console.warn('[sw] skipped', url, e.message); }
    }));
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map(k => (k.startsWith('baba-catalogue-') && k !== CACHE)
      ? caches.delete(k) : Promise.resolve()));
    await self.clients.claim();
  })());
});

// Lets the page trigger an immediate update instead of waiting for all tabs to close.
self.addEventListener('message', event => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // leave cross-origin alone
  // check.html asks for ?nosw= so it can see what the SERVER really has,
  // rather than being answered from this cache.
  if (url.searchParams.has('nosw')) return;

  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match('./index.html');
      if (cached) {
        // Serve instantly, refresh in the background for next launch.
        event.waitUntil((async () => {
          try {
            const fresh = await fetch('./index.html', { cache: 'reload' });
            if (fresh && fresh.ok) await cache.put('./index.html', fresh.clone());
          } catch (e) {}
        })());
        return cached;
      }
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put('./index.html', res.clone());
        return res;
      } catch (e) {
        return cached || Response.error();
      }
    })());
    return;
  }

  // Staff publish products-extra.json without a rebuild, so it must not be
  // trapped behind a cache-first strategy.
  if (url.pathname.endsWith('/products-extra.json')) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const fresh = await fetch(req, { cache: 'no-cache' });
        if (fresh && fresh.ok) cache.put(req, fresh.clone());
        return fresh;
      } catch (e) {
        return (await cache.match(req)) || new Response('{}', { headers: { 'Content-Type': 'application/json' } });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    } catch (e) {
      return cached || Response.error();
    }
  })());
});
